---
- hosts: dbserver
  become: yes
  pre_tasks:
    - name: Install the latest version of nginx
      ansible.builtin.yum:
        name: nginx
        state: latest
  roles:
   - role: 'roles/HSC/monitoring'
     tags:
       - hold_HSC
   - role: 'roles/common/webtier'
     tags:
       - hold_common
  
