---
- name: Create additional configuration
  template:
    src: "hardening.conf.j2"
    dest: "{{ nginx_configuration_dir }}/conf.d/90.hardening.conf"
    mode: '0600'
    owner: "{{ nginx_owner_user }}"
    group: "{{ nginx_owner_group }}"
  notify: Restart nginx
